version: '3'

services:
  payload:
    image: node:20-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - sqlite_data:/home/node/app/data
      - media:/home/node/app/public/media
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    env_file:
      - .env

volumes:
  sqlite_data:
  media:
  node_modules:
